ivon:
  learning_rate: 0.3
  num_epochs: 500
  batch_size: 128
  weight_decay: 1.0e-5
  clip_radius: 1.0e-3
  ess: 60000.0
  hess_init: 0.5
  diffusion_timesteps: 1000
  train_mc_samples: 1
  rescale_lr: False
